# Generated by Django 3.0.4 on 2020-04-30 01:17

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_auto_20200429_1024"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="picture",
            field=cloudinary.models.CloudinaryField(
                max_length=255, verbose_name="Imagem do evento"
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="picture",
            field=cloudinary.models.CloudinaryField(
                max_length=255, verbose_name="Foto"
            ),
        ),
    ]
