# Generated by Django 3.0.4 on 2020-04-29 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200429_0354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='price',
            field=models.FloatField(blank=True, null=True, verbose_name='Valor (R$)'),
        ),
    ]
