# Generated by Django 3.0.4 on 2020-04-12 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_post_published_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Publisher',
            new_name='Member',
        ),
    ]
