# Generated by Django 3.0.4 on 2020-03-29 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200329_1256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='does_repeat',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='repetition_quantity',
        ),
        migrations.AlterField(
            model_name='schedule',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Horário de fim'),
        ),
    ]
