# Generated by Django 3.0.4 on 2020-04-30 03:59

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200429_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postfile',
            name='post_file',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='Arquivo'),
        ),
    ]
