# Generated by Django 3.0.4 on 2020-04-08 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200329_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='background_image',
            field=models.ImageField(default='', upload_to='group_images/', verbose_name='Imagem do grupo'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Church',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('address', models.CharField(max_length=250, verbose_name='Endereço')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('last_updated_date', models.DateTimeField(auto_now=True, verbose_name='Última modificação')),
                ('chief_pastor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Publisher', verbose_name='Pastor Principal')),
            ],
            options={
                'verbose_name': 'Igreja',
                'verbose_name_plural': 'Igrejas',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='group',
            name='church',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Church', verbose_name='Igreja'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Church', verbose_name='Local'),
        ),
    ]
