# Generated by Django 3.0.4 on 2020-05-01 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200501_0241'),
    ]

    operations = [
        migrations.AddField(
            model_name='church',
            name='acronym',
            field=models.CharField(default='IBCC 2', max_length=15, verbose_name='Sigla'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='EventInterests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interested_people_count', models.IntegerField(default=0, verbose_name='Pessoas Interessadas')),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Event', verbose_name='Evento')),
            ],
            options={
                'verbose_name': 'Pessoas Interessas em Eventos',
                'verbose_name_plural': 'Pessoas Interessadas',
                'ordering': ['-interested_people_count'],
            },
        ),
    ]
