# Generated by Django 3.0.4 on 2020-04-11 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200408_0131'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_name', models.CharField(max_length=100, verbose_name='Nome')),
                ('donor_email', models.EmailField(max_length=254, verbose_name='Email')),
                ('donate_type', models.CharField(choices=[('tithe', 'Dízimo'), ('offer', 'Oferta')], max_length=20, verbose_name='Tipo de Oferta')),
                ('payment_option', models.CharField(choices=[('deposit', 'Depósito'), ('pagseguro', 'PagSeguro'), ('paypal', 'Paypal')], default='deposit', max_length=20, verbose_name='Opção de Pagamento')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('last_updated_date', models.DateTimeField(auto_now=True, verbose_name='Última modificação')),
            ],
            options={
                'verbose_name': 'Doação',
                'verbose_name_plural': 'Doações',
                'ordering': ['-creation_date'],
            },
        ),
    ]
