# Generated by Django 3.0.4 on 2020-04-11 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_donate'),
    ]

    operations = [
        migrations.AddField(
            model_name='donate',
            name='amount',
            field=models.FloatField(default=0, verbose_name='Valor'),
            preserve_default=False,
        ),
    ]
