# Generated by Django 3.0.4 on 2020-04-11 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_donate_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='donate',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('done', 'Concluído')], default='pending', max_length=20, verbose_name='Status do Pagamento'),
        ),
        migrations.AlterField(
            model_name='donate',
            name='payment_option',
            field=models.CharField(choices=[('deposit', 'Depósito'), ('pagseguro', 'PagSeguro'), ('paypal', 'Paypal')], max_length=20, verbose_name='Opção de Pagamento'),
        ),
    ]
