# Generated by Django 3.0.4 on 2020-05-01 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200501_1535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='interested_people_count',
        ),
        migrations.AlterField(
            model_name='eventinterests',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interests', to='core.Event', verbose_name='Evento'),
        ),
    ]
