# Generated by Django 3.0.4 on 2020-04-12 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200411_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donate',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('done', 'Concluído'), ('excluded', 'Excluído')], default='pending', max_length=20, verbose_name='Status do Pagamento'),
        ),
    ]
