# Generated by Django 3.0.4 on 2020-05-01 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20200501_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='interested_people_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Pessoas Interessadas'),
        ),
        migrations.DeleteModel(
            name='EventInterests',
        ),
    ]
