# Generated by Django 3.0.4 on 2020-04-23 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20200422_2137'),
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='organizing_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='groups.Group', verbose_name='Grupo Organizador'),
        ),
        migrations.DeleteModel(
            name='Group',
        ),
    ]
