# Generated by Django 3.0.4 on 2020-04-12 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_donate_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donate',
            name='reference',
            field=models.CharField(max_length=20, verbose_name='Referência'),
        ),
    ]
