# Generated by Django 3.0.4 on 2020-04-24 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20200422_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='address',
            field=models.CharField(default='Curado', max_length=100, verbose_name='Endereço'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Data de nascimento'),
        ),
    ]
