# Generated by Django 3.0.4 on 2020-04-12 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20200412_0334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donate',
            name='reference',
        ),
    ]
