# Generated by Django 3.0.4 on 2020-05-02 03:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_auto_20200501_1559"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schedule",
            name="title",
            field=models.CharField(
                choices=[
                    ("doutrina", "Culto de Doutrina"),
                    ("ebd", "Escola Bíblica Dominical"),
                    ("intercessao", "Culto de Intercessão"),
                    ("domingo", "Culto de Domingo"),
                    ("ceia", "Ceia do Senhor"),
                    ("casa", "Cultuando em casa"),
                ],
                max_length=20,
                verbose_name="Encontro",
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="category",
            field=models.CharField(
                choices=[
                    ("doutrina", "Culto de Doutrina"),
                    ("ebd", "Escola Bíblica Dominical"),
                    ("intercessao", "Culto de Intercessão"),
                    ("domingo", "Culto de Domingo"),
                    ("ceia", "Ceia do Senhor"),
                    ("casa", "Cultuando em casa"),
                ],
                max_length=20,
                verbose_name="Categoria",
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="youtube_video_code",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="Código do Youtube"
            ),
        ),
        migrations.CreateModel(
            name="MembersUnion",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "union_type",
                    models.CharField(
                        choices=[
                            ("compromisso", "Compromisso"),
                            ("noivado", "Noivado"),
                            ("casamento", "Casamento"),
                        ],
                        max_length=20,
                        verbose_name="Tipo da união",
                    ),
                ),
                ("union_date", models.DateTimeField(verbose_name="Data da união")),
                (
                    "creation_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "last_updated_date",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última modificação"
                    ),
                ),
                (
                    "man",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="man",
                        to="core.Member",
                        verbose_name="Homem",
                    ),
                ),
                (
                    "woman",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="woman",
                        to="core.Member",
                        verbose_name="Mulher",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vídeo",
                "verbose_name_plural": "Vídeos",
                "ordering": ["-union_date"],
            },
        ),
    ]
