# Generated by Django 3.0.4 on 2020-04-26 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20200424_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='church_function',
            field=models.CharField(default='Membro', max_length=40, verbose_name='Função na Igreja'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='nickname',
            field=models.CharField(default='', max_length=25, verbose_name='Conhecido como'),
            preserve_default=False,
        ),
    ]
