# Generated by Django 3.0.4 on 2020-04-12 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_donate_reference'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-published_date'], 'verbose_name': 'Postagem', 'verbose_name_plural': 'Postagens'},
        ),
        migrations.RemoveField(
            model_name='post',
            name='last_updated_date',
        ),
    ]
