# Generated by Django 3.0.4 on 2020-04-12 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20200412_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='last_updated_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Última modificação'),
        ),
    ]
