# Generated by Django 3.0.4 on 2020-05-03 15:01

import core.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20200502_0059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='picture',
        ),
        migrations.RemoveField(
            model_name='member',
            name='picture',
        ),
        migrations.AlterField(
            model_name='postfile',
            name='post_file',
            field=core.models.CloudinaryField(max_length=255, verbose_name='Arquivo'),
        ),
    ]
