# Generated by Django 3.0.4 on 2020-04-26 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='picture',
            field=models.ImageField(default='default', upload_to='pictures/', verbose_name='Foto'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='VideoReaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claps_count', models.IntegerField(default=0, verbose_name='Gostei')),
                ('dislike_count', models.IntegerField(default=0, verbose_name='Não gostei')),
                ('video', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Video', verbose_name='Vídeo')),
            ],
            options={
                'verbose_name': 'Reação',
                'verbose_name_plural': 'Reações',
                'ordering': ['-claps_count', '-dislike_count'],
            },
        ),
        migrations.CreateModel(
            name='PostReaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claps_count', models.IntegerField(default=0, verbose_name='Gostei')),
                ('dislike_count', models.IntegerField(default=0, verbose_name='Não gostei')),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Post', verbose_name='Postagem')),
            ],
            options={
                'verbose_name': 'Reação',
                'verbose_name_plural': 'Reações',
                'ordering': ['-claps_count', '-dislike_count'],
            },
        ),
    ]
