# Generated by Django 3.0.4 on 2020-04-12 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_post_last_updated_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='last_updated_date',
        ),
    ]
