# Generated by Django 3.0.4 on 2020-04-29 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20200426_1459'),
    ]

