# Generated by Django 3.0.4 on 2020-04-29 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20200426_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='picture',
            field=models.ImageField(default='default', upload_to='event_images/', verbose_name='Imagem do evento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Video', verbose_name='Vídeo'),
        ),
    ]
