# Generated by Django 3.0.4 on 2020-05-03 15:07

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_auto_20200503_1201"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="picture",
            field=cloudinary.models.CloudinaryField(
                default="default", max_length=255, verbose_name="Imagem do evento"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="member",
            name="picture",
            field=cloudinary.models.CloudinaryField(
                default="default", max_length=255, verbose_name="Foto"
            ),
            preserve_default=False,
        ),
    ]
