# Generated by Django 3.0.4 on 2020-04-29 04:15

import birthday.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20200429_0107'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postreaction',
            options={'ordering': ['-claps_count', '-dislike_count'], 'verbose_name': 'Reação ao Post', 'verbose_name_plural': 'Reações aos Posts'},
        ),
        migrations.AlterModelOptions(
            name='postview',
            options={'ordering': ['-views_count'], 'verbose_name': 'Visualização da Postagem', 'verbose_name_plural': 'Visualizações das Postagens'},
        ),
        migrations.AlterModelOptions(
            name='videoreaction',
            options={'ordering': ['-claps_count', '-dislike_count'], 'verbose_name': 'Reação ao Vídeo', 'verbose_name_plural': 'Reações aos vídeos'},
        ),
        migrations.AddField(
            model_name='member',
            name='birthday',
            field=birthday.fields.BirthdayField(default='default'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='birthday_dayofyear_internal',
            field=models.PositiveSmallIntegerField(default=None, editable=False, null=True),
        ),
        migrations.CreateModel(
            name='VideoView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('views_count', models.IntegerField(default=0, verbose_name='Visualizações')),
                ('video', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Post', verbose_name='Postagem')),
            ],
            options={
                'verbose_name': 'Visualização do Vídeo',
                'verbose_name_plural': 'Visualizações dos Vídeos',
                'ordering': ['-views_count'],
            },
        ),
    ]
