# Generated by Django 3.0.4 on 2020-04-29 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20200429_0115'),
    ]

    operations = [
       migrations.AlterField(
            model_name='event',
            name='picture',
            field=models.ImageField(default='default', upload_to='event_images/', verbose_name='Imagem do evento'),
            preserve_default=False,
        ),
    ]
