# Generated by Django 3.0.4 on 2020-04-29 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20200429_0118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='video',
        ),
    ]
