# Generated by Django 3.0.4 on 2020-05-05 02:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_auto_20200504_1922"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schedule",
            name="leader",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="dirigente",
                to="core.Member",
                verbose_name="Dirigente",
            ),
        ),
    ]
