# Generated by Django 3.0.4 on 2020-05-05 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20200504_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Descrição'),
        ),
    ]
