# Generated by Django 3.0.4 on 2020-04-29 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_remove_schedule_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Video', verbose_name='Vídeo'),
        ),
    ]
