# Generated by Django 3.0.4 on 2020-04-29 04:27

import birthday.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_schedule_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='birthday',
            field=birthday.fields.BirthdayField(blank=True, null=True, verbose_name='Aniversário'),
        ),
    ]
