# Generated by Django 3.0.4 on 2020-04-29 04:33

import birthday.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20200429_0127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='birthday',
        ),
        migrations.AddField(
            model_name='member',
            name='date_of_birth_dayofyear_internal',
            field=models.PositiveSmallIntegerField(default=None, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='date_of_birth',
            field=birthday.fields.BirthdayField(blank=True, null=True, verbose_name='Data de nascimento'),
        ),
    ]
