# Generated by Django 3.0.4 on 2020-06-24 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_auto_20200529_0025'),
    ]

    operations = [
        migrations.AddField(
            model_name='church',
            name='is_congregation',
            field=models.BooleanField(default=False, verbose_name='Congregação'),
        ),
        migrations.AddField(
            model_name='church',
            name='responsible',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible', to='core.Member', verbose_name='Responsável'),
        ),
        migrations.AlterField(
            model_name='church',
            name='acronym',
            field=models.CharField(max_length=25, verbose_name='Sigla'),
        ),
        migrations.AlterField(
            model_name='church',
            name='chief_pastor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chief_pastor', to='core.Member', verbose_name='Pastor Principal'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='category',
            field=models.CharField(choices=[('PRESENCIAL', 'Presencial'), ('ONLINE', 'Online'), ('HIBRIDO', 'Online e Presencial')], max_length=15, verbose_name='Tipo'),
        ),
    ]
