# Generated by Django 3.0.4 on 2020-06-24 16:04

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_auto_20200624_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='church',
            name='background_image',
            field=cloudinary.models.CloudinaryField(default='default', max_length=255, verbose_name='Foto da Igreja'),
            preserve_default=False,
        ),
    ]
