# Generated by Django 3.0.4 on 2020-06-24 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0030_church_background_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="church",
            name="chief_pastor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="chief_pastor",
                to="core.Member",
                verbose_name="Pastor Principal",
            ),
        ),
        migrations.AlterField(
            model_name="church",
            name="responsible",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="responsible",
                to="core.Member",
                verbose_name="Responsável",
            ),
        ),
    ]
