# Generated by Django 3.0.4 on 2021-08-10 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0034_auto_20210810_1217"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="member",
            name="email",
        ),
        migrations.RemoveField(
            model_name="member",
            name="facebook",
        ),
        migrations.RemoveField(
            model_name="member",
            name="instagram",
        ),
        migrations.RemoveField(
            model_name="member",
            name="whatsapp",
        ),
    ]
