# Generated by Django 3.0.4 on 2021-12-27 14:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_auto_20211208_0334'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membersunion',
            options={'ordering': ['-union_date'], 'verbose_name': 'Relacionamento', 'verbose_name_plural': 'Relacionamentos'},
        ),
        migrations.AddField(
            model_name='member',
            name='baptism_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de batismo'),
        ),
        migrations.AddField(
            model_name='member',
            name='children',
            field=models.PositiveIntegerField(default=0, verbose_name='Tem quantos filhos'),
        ),
        migrations.AddField(
            model_name='member',
            name='conversion_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de conversão'),
        ),
        migrations.AddField(
            model_name='member',
            name='have_a_job',
            field=models.BooleanField(default=True, verbose_name='Trabalha atualmente'),
        ),
        migrations.AddField(
            model_name='member',
            name='is_retired',
            field=models.BooleanField(default=False, verbose_name='É aposentado'),
        ),
        migrations.AddField(
            model_name='member',
            name='job_title',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Profissão'),
        ),
        migrations.AddField(
            model_name='member',
            name='registration_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Data do cadastro'),
        ),
        migrations.AddField(
            model_name='member',
            name='work_on_sundays',
            field=models.BooleanField(default=False, verbose_name='Trabalha aos domingos'),
        ),
        migrations.AlterField(
            model_name='member',
            name='address',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='member',
            name='church_function',
            field=models.CharField(blank=True, choices=[('lider_de_departamento', 'Líder de Grupo ou Departamento'), ('lideranca_de_departamento', 'Liderança de Grupo ou Departamento'), ('pastor_principal', 'Pastor Principal'), ('pastor_auxiliar', 'Pastor Auxiliar'), ('professor_de_ebd', 'Professor de EBD'), ('secretario_de_ebd', 'Secretário de sala de EBD'), ('superintendente', 'Superintendente'), ('membro', 'Membro')], max_length=50, null=True, verbose_name='Função na Igreja'),
        ),
        migrations.AlterField(
            model_name='member',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('solteiro', 'Solteiro (a)'), ('casado', 'Casado (a)'), ('divorciado', 'Divorciado (a)'), ('viuvo', 'Viúvo (a)')], max_length=30, null=True, verbose_name='Estado civil'),
        ),
    ]
