# Generated by Django 3.0.4 on 2021-12-27 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_auto_20211227_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membersunion',
            name='union_date',
            field=models.DateField(verbose_name='Data da união'),
        ),
    ]
