# Generated by Django 3.0.4 on 2022-02-20 15:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0044_auto_20211229_1807"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="member",
            options={
                "ordering": ["name"],
                "verbose_name": "Pessoa",
                "verbose_name_plural": "Pessoas",
            },
        ),
        migrations.AlterField(
            model_name="member",
            name="church_relation",
            field=models.CharField(
                blank=True,
                choices=[
                    ("membro", "Membro"),
                    ("congregado", "Congregado"),
                    ("convidado", "Convidado"),
                ],
                max_length=20,
                null=True,
                verbose_name="Relação com a Igreja",
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="user",
            field=models.OneToOneField(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuário",
            ),
        ),
    ]
