# Generated by Django 3.0.4 on 2022-02-20 15:34

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_auto_20220220_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='picture',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Foto'),
        ),
    ]
