# Generated by Django 3.0.4 on 2022-05-19 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0046_auto_20220220_1234"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="church_function",
            field=models.CharField(
                blank=True,
                choices=[
                    ("corpo_diaconal", "Corpo Diaconal"),
                    ("lider_de_departamento", "Líder de Grupo ou Departamento"),
                    ("lideranca_de_departamento", "Liderança de Grupo ou Departamento"),
                    ("pastor_principal", "Pastor Principal"),
                    ("pastor_auxiliar", "Pastor Auxiliar"),
                    ("professor_de_ebd", "Professor de EBD"),
                    ("secretario_de_ebd", "Secretário de sala de EBD"),
                    ("superintendente", "Superintendente"),
                    ("membro", "Membro"),
                ],
                max_length=50,
                null=True,
                verbose_name="Função na Igreja",
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="educational_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("educacao_infantil", "Educação infantil"),
                    ("ensino_fundamental", "Ensino fundamental"),
                    ("ensino_medio", "Ensino médio"),
                    ("ensino_superior", "Ensino superior"),
                    ("ensino_superior_incompleto", "Ensino superior Incompleto"),
                    ("pos_graduacao", "Pós-graduação"),
                    ("mestrado", "Mestrado"),
                    ("doutorado", "Doutorado"),
                ],
                max_length=50,
                null=True,
                verbose_name="Grau de escolaridade",
            ),
        ),
    ]
