# Generated by Django 3.0.4 on 2025-01-18 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0048_auto_20220806_1243"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="membersunion",
            name="man",
        ),
        migrations.RemoveField(
            model_name="membersunion",
            name="woman",
        ),
        migrations.AddField(
            model_name="membersunion",
            name="person_one",
            field=models.OneToOneField(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="person_one",
                to="core.Member",
                verbose_name="Cônjuge 1",
            ),
        ),
        migrations.AddField(
            model_name="membersunion",
            name="person_two",
            field=models.OneToOneField(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="person_two",
                to="core.Member",
                verbose_name="Cônjuge 2",
            ),
        ),
    ]
