# Generated by Django 3.0.4 on 2025-01-18 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0049_auto_20250118_1326"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membersunion",
            name="person_one",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="person_one",
                to="core.Member",
                verbose_name="Cônjuge",
            ),
        ),
        migrations.AlterField(
            model_name="membersunion",
            name="person_two",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="person_two",
                to="core.Member",
                verbose_name="Cônjuge",
            ),
        ),
        migrations.AlterField(
            model_name="membersunion",
            name="union_type",
            field=models.CharField(
                choices=[
                    ("compromisso", "Compromisso"),
                    ("noivado", "Noivado"),
                    ("casamento", "Casamento"),
                ],
                default="casamento",
                max_length=20,
                verbose_name="Tipo da união",
            ),
        ),
    ]
