# Generated by Django 3.0.4 on 2025-01-19 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0050_auto_20250118_1402"),
    ]

    operations = [
        migrations.AddField(
            model_name="membersunion",
            name="person_two_external",
            field=models.CharField(
                blank=True, default=None, max_length=150, verbose_name="Nome do cônjuge"
            ),
        ),
        migrations.AlterField(
            model_name="membersunion",
            name="person_two",
            field=models.OneToOneField(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="person_two",
                to="core.Member",
                verbose_name="Cônjuge",
            ),
        ),
    ]
