# Generated by Django 3.0.4 on 2025-01-19 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0051_auto_20250119_1950"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="membersunion",
            name="person_two_external",
        ),
        migrations.AlterField(
            model_name="membersunion",
            name="person_two",
            field=models.OneToOneField(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="person_two",
                to="core.Member",
                verbose_name="Cônjuge",
            ),
        ),
    ]
