# Generated by Django 3.2 on 2025-04-10 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0054_auto_20250216_1320"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="name",
            field=models.CharField(max_length=200, verbose_name="Nome"),
        ),
    ]
