# Generated by Django 3.2 on 2025-04-10 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0055_alter_member_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="membersunion",
            name="person_two_external",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Cônjuge externo"
            ),
        ),
    ]
