# Generated by Django 3.2 on 2025-04-12 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0056_membersunion_person_two_external"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="visilibity",
            field=models.CharField(
                choices=[("public", "Público"), ("private", "Privado")],
                default="private",
                max_length=10,
                verbose_name="Visibilidade",
            ),
        ),
    ]
