# Generated by Django 3.2 on 2025-04-12 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0057_post_visilibity"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="visilibity",
            new_name="visibility",
        ),
    ]
