# Generated by Django 3.2 on 2025-04-13 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0058_rename_visilibity_post_visibility"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="church_function",
            field=models.CharField(
                blank=True,
                choices=[
                    ("corpo_diaconal", "Corpo Diaconal"),
                    ("lider_de_departamento", "Líder de Grupo ou Departamento"),
                    ("lideranca_de_departamento", "Liderança de Grupo ou Departamento"),
                    ("pastor_principal", "Pastor Principal"),
                    ("pastor_auxiliar", "Pastor Auxiliar"),
                    ("professor_de_ebd", "Professor de EBD"),
                    ("secretario_de_ebd", "Secretário de sala de EBD"),
                    ("superintendente", "Superintendente"),
                    ("membro", "Membro"),
                    ("lider_de_congregacao", "Líder de Congregação"),
                    ("evangelista", "Evangelista"),
                ],
                max_length=50,
                null=True,
                verbose_name="Função na Igreja",
            ),
        ),
    ]
