# Generated by Django 3.2 on 2025-07-20 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0059_alter_member_church_function"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="outside_church_region",
            field=models.BooleanField(
                default=False, verbose_name="Membro fora da região da Igreja"
            ),
        ),
    ]
