# Generated by Django 3.2 on 2025-07-26 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0060_member_outside_church_region"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="outside_church_region",
            field=models.BooleanField(
                default=False, verbose_name="Membro temporariamente ausente da Igreja"
            ),
        ),
    ]
