# Generated by Django 3.2 on 2026-02-21 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0061_alter_member_outside_church_region"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="Email"
            ),
        ),
    ]
