# Generated by Django 3.2 on 2026-02-21 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0062_member_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="member",
            name="outside_church_region",
        ),
        migrations.AddField(
            model_name="member",
            name="outside_church",
            field=models.BooleanField(default=False, verbose_name="Membro inativo"),
        ),
    ]
