# Generated by Django 3.0.4 on 2021-12-29 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0043_auto_20211229_1725"),
        ("ebd", "0003_auto_20211208_0355"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ebdclass",
            name="secretaries",
            field=models.ManyToManyField(
                blank=True,
                related_name="Secretário",
                to="core.Member",
                verbose_name="Secretários",
            ),
        ),
        migrations.AlterField(
            model_name="ebdclass",
            name="students",
            field=models.ManyToManyField(
                blank=True,
                related_name="Aluno",
                to="core.Member",
                verbose_name="Alunos",
            ),
        ),
        migrations.AlterField(
            model_name="ebdclass",
            name="teachers",
            field=models.ManyToManyField(
                blank=True,
                related_name="Professor",
                to="core.Member",
                verbose_name="Professores",
            ),
        ),
    ]
