# Generated by Django 3.0.4 on 2022-02-22 03:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_auto_20220220_1234'),
        ('ebd', '0004_auto_20211229_1725'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EBDClassLesson',
            new_name='EBDLesson',
        ),
        migrations.CreateModel(
            name='EBDPresenceRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('last_updated_date', models.DateTimeField(auto_now=True, verbose_name='Última modificação')),
                ('attended', models.BooleanField(default=False, verbose_name='Presente')),
                ('register_on', models.DateTimeField(blank=True, null=True, verbose_name='Registro em')),
                ('church', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Church', verbose_name='Igreja')),
                ('ebd_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ebd.EBDClass', verbose_name='Classe')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ebd.EBDLesson', verbose_name='Lição')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student', to='core.Member', verbose_name='Aluno')),
            ],
            options={
                'verbose_name': 'Registro de Presença na aula',
                'verbose_name_plural': 'Registros de Presença nas aulas',
                'ordering': ['-creation_date'],
            },
        ),
    ]
