# Generated by Django 3.0.4 on 2022-02-22 03:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ebd", "0005_auto_20220222_0027"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ebdpresencerecord",
            options={
                "ordering": ["-creation_date"],
                "verbose_name": "Registro de Presença",
                "verbose_name_plural": "Registro de Presenças",
            },
        ),
        migrations.RemoveField(
            model_name="ebdpresencerecord",
            name="last_updated_date",
        ),
        migrations.AddField(
            model_name="ebdpresencerecord",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Criado por",
            ),
        ),
    ]
