# Generated by Django 3.0.4 on 2022-02-22 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_auto_20220220_1234'),
        ('ebd', '0006_auto_20220222_0045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebdpresencerecord',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_presence_record', to='core.Member', verbose_name='Aluno'),
        ),
    ]
