# Generated by Django 3.0.4 on 2022-02-22 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ebd", "0007_auto_20220222_0123"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ebdpresencerecord",
            old_name="church",
            new_name="ebd_church",
        ),
    ]
