# Generated by Django 3.0.4 on 2022-03-23 03:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ebd', '0010_ebdpresencerecord_justification'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebdpresencerecord',
            name='register_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presence_record_register_by', to=settings.AUTH_USER_MODEL, verbose_name='Última atualização por'),
        ),
        migrations.AlterField(
            model_name='ebdpresencerecord',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presence_record_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Criado por'),
        ),
    ]
