# Generated by Django 3.0.4 on 2022-03-23 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ebd", "0011_auto_20220323_0033"),
    ]

    operations = [
        migrations.AddField(
            model_name="ebdlesson",
            name="magazine_title",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Lição"
            ),
        ),
    ]
