# Generated by Django 3.0.4 on 2022-03-23 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebd', '0012_ebdlesson_magazine_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebdlesson',
            name='magazine_title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Revista'),
        ),
    ]
