# Generated by Django 3.0.4 on 2022-05-19 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_auto_20220519_0208'),
        ('ebd', '0013_auto_20220323_0042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ebdpresencerecord',
            name='student',
        ),
        migrations.AddField(
            model_name='ebdpresencerecord',
            name='person',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='person_presence_record', to='core.Member', verbose_name='Pessoa'),
            preserve_default=False,
        ),
    ]
