# Generated by Django 3.0.4 on 2022-06-17 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ebd', '0014_auto_20220519_0208'),
    ]

    operations = [
        migrations.CreateModel(
            name='EBDLessonClassDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitors_quantity', models.PositiveIntegerField(default=0, verbose_name='Número de visitantes')),
                ('money_raised', models.FloatField(blank=True, null=True, verbose_name='Dinheiro arrecadado')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('last_updated_date', models.DateTimeField(auto_now=True, verbose_name='Última modificação')),
                ('ebd_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ebd.EBDClass', verbose_name='Classe')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ebd.EBDLesson', verbose_name='Lição')),
            ],
            options={
                'verbose_name': 'Detalhes da classe na lição',
                'verbose_name_plural': 'Detalhes das classes nas lições',
                'ordering': ['-last_updated_date'],
            },
        ),
    ]
