# Generated by Django 3.2 on 2025-05-31 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ebd", "0017_auto_20230107_1108"),
    ]

    operations = [
        migrations.AddField(
            model_name="ebdclass",
            name="is_active",
            field=models.BooleanField(
                default=True, help_text="Classe ativa ou inativa", verbose_name="Ativa"
            ),
        ),
    ]
