# Generated by Django 4.2.30 on 2026-08-11 22:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0064_alter_audit_id_alter_church_id_alter_donate_id_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ebd", "0018_ebdclass_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ebdclass",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="ebdlabeloptions",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="ebdlesson",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="ebdlessonclassdetails",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="ebdpresencerecord",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="ebdpresencerecordlabels",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.CreateModel(
            name="EBDClassMemberJoinRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ebd_class_member_type",
                    models.CharField(
                        choices=[
                            ("student", "Aluno"),
                            ("teacher", "Professor"),
                            ("secretary", "Secretário"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de membro",
                    ),
                ),
                (
                    "request_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data da solicitação"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendente"),
                            ("approved", "Aprovado"),
                            ("rejected", "Rejeitado"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "manager_decision_date",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Data da decisão do responsável",
                    ),
                ),
                (
                    "manager_decision_reason",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Motivo da decisão do responsável",
                    ),
                ),
                (
                    "ebd_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ebd.ebdclass",
                        verbose_name="Classe",
                    ),
                ),
                (
                    "manager",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ebd_class_member_join_request_manager",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Gerenciado por",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.member",
                        verbose_name="Membro",
                    ),
                ),
            ],
            options={
                "verbose_name": "Solicitação de admissão de membro na classe",
                "verbose_name_plural": "Solicitações de admissão de membros nas classes",
                "ordering": ["-request_date"],
            },
        ),
    ]
