# Generated by Django 4.2.30 on 2026-08-11 22:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ebd", "0019_alter_ebdclass_id_alter_ebdlabeloptions_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ebdclassmemberjoinrequest",
            name="manager",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ebd_class_member_join_request_manager",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Responsável",
            ),
        ),
    ]
