# Generated by Django 3.0.4 on 2020-05-08 03:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0002_auto_20200429_2217"),
    ]

    operations = [
        migrations.CreateModel(
            name="GroupMeetingDate",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateTimeField(verbose_name="Horário de início")),
                (
                    "end_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Horário de fim"
                    ),
                ),
                (
                    "creation_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="groups.Group",
                        verbose_name="Grupo",
                    ),
                ),
            ],
        ),
    ]
