# Generated by Django 3.0.4 on 2020-05-08 03:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0004_auto_20200508_0024"),
    ]

    operations = [
        migrations.AlterField(
            model_name="groupmeetingdate",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="groups",
                to="groups.Group",
                verbose_name="Grupo",
            ),
        ),
    ]
