# Generated by Django 3.0.4 on 2020-05-08 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0005_auto_20200508_0049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmeetingdate',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_dates', to='groups.Group', verbose_name='Grupo'),
        ),
    ]
