# Generated by Django 4.2.30 on 2026-08-11 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0011_auto_20210810_1238"),
    ]

    operations = [
        migrations.AlterField(
            model_name="generalcategory",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="group",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="groupmeetingdate",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
